import {
  Semester,
  Course,
  CourseDate,
  CourseTask,
  CourseTopic,
} from './types';

export const DEFAULT_SEMESTER_ID = 'sem_1_podzim_2026';

export function getInitialSemesters(ownerId: string): Semester[] {
  return [
    {
      id: DEFAULT_SEMESTER_ID,
      ownerId,
      title: '1. semestr',
      academicYear: '2026/2027',
      period: 'Podzim',
      order: 1,
    },
  ];
}

export function getInitialCourses(ownerId: string, semesterId = DEFAULT_SEMESTER_ID): Course[] {
  return [
    {
      id: 'course_AI001',
      ownerId,
      semesterId,
      code: 'AI001',
      name: 'Elements of AI',
      teacher: 'doc. RNDr. Tomáš Brázdil, Ph.D.',
      room: 'Online / FI MUNI',
      scheduleSummary: 'Samořízené studium (Online)',
      completionType: 'Zápočet',
      credits: 2,
      isCompleted: false,
      order: 1,
    },
    {
      id: 'course_ISKB02',
      ownerId,
      semesterId,
      code: 'ISKB02',
      name: 'Úvod do knihovnictví',
      teacher: 'PhDr. Petr Škyřík, Ph.D.',
      room: 'Učebna A22',
      scheduleSummary: 'Út 10:00–11:40',
      completionType: 'Zkouška',
      credits: 5,
      isCompleted: false,
      order: 2,
    },
    {
      id: 'course_ISKB03',
      ownerId,
      semesterId,
      code: 'ISKB03',
      name: 'Informační služby a vyhledávání',
      teacher: 'Mgr. Pavlína Mazáčová, Ph.D.',
      room: 'Učebna B2.23',
      scheduleSummary: 'St 12:00–13:40',
      completionType: 'Zkouška',
      credits: 5,
      isCompleted: false,
      order: 3,
    },
    {
      id: 'course_ISKB04',
      ownerId,
      semesterId,
      code: 'ISKB04',
      name: 'Psaní odborných textů',
      teacher: 'Mgr. Michal Černý, Ph.D.',
      room: 'Učebna C33',
      scheduleSummary: 'Čt 08:00–09:40',
      completionType: 'Zápočet',
      credits: 4,
      isCompleted: false,
      order: 4,
    },
    {
      id: 'course_ISKB08',
      ownerId,
      semesterId,
      code: 'ISKB08',
      name: 'Literatura v kulturním kontextu',
      teacher: 'prof. PhDr. Jiří Trávníček, M.A.',
      room: 'Posluchárna A11',
      scheduleSummary: 'Po 14:00–15:40',
      completionType: 'Kolokvium',
      credits: 4,
      isCompleted: false,
      order: 5,
    },
    {
      id: 'course_ISKB60',
      ownerId,
      semesterId,
      code: 'ISKB60',
      name: 'Prolegomena k oboru',
      teacher: 'PhDr. Ladislava Zbiejczuk Suchá, Ph.D.',
      room: 'Bloková výuka / KISK',
      scheduleSummary: 'Úvodní soustředění',
      completionType: 'Zápočet',
      credits: 4,
      isCompleted: true,
      order: 6,
    },
    {
      id: 'course_ISKB65',
      ownerId,
      semesterId,
      code: 'ISKB65',
      name: 'Blok expertů',
      teacher: 'Hostující přednášející KISK',
      room: 'Posluchárna B2.13',
      scheduleSummary: 'Pá 10:00–13:20 (vybrané týdny)',
      completionType: 'Kolokvium',
      credits: 3,
      isCompleted: false,
      order: 7,
    },
    {
      id: 'course_PHK0001',
      ownerId,
      semesterId,
      code: 'PHK0001',
      name: 'Filozofie pro posluchače nefilozofických oborů',
      teacher: 'doc. PhDr. Josef Zouhar, CSc.',
      room: 'Posluchárna A11',
      scheduleSummary: 'St 16:00–17:40',
      completionType: 'Zkouška',
      credits: 4,
      isCompleted: false,
      order: 8,
    },
  ];
}

export function getInitialTopics(ownerId: string, semesterId = DEFAULT_SEMESTER_ID): CourseTopic[] {
  return [
    {
      id: 'topic_ai_1',
      ownerId,
      semesterId,
      courseId: 'course_AI001',
      title: 'Kapitola 1: Co je to umělá inteligence (autononomie a adaptabilita)',
      weekLabel: '1. týden',
      isProcessed: true,
      notes: `## Definice umělé inteligence\n- **Autonomie**: schopnost vykonávat úkoly ve složitém prostředí bez neustálého vedení uživatelem.\n- **Adaptabilita**: schopnost zlepšovat výkon učením se ze zkušeností.\n\n### Související oblasti\n- Strojové učení (Machine Learning): systémy, které zlepšují svou výkonnost s větším množstvím dat.\n- Hluboké učení (Deep Learning): podoblast využívající vícevrstvé neuronové sítě.\n\n### Klíčové poznámky ke testu\n- Turingův test neověřuje skutečné vědomí, ale napodobení lidské konverzace.\n- Rozdíl mezi úzkou (narrow AI) a obecnou (AGI) inteligencí.`,
    },
    {
      id: 'topic_ai_2',
      ownerId,
      semesterId,
      courseId: 'course_AI001',
      title: 'Kapitola 2: Řešení problémů pomocí AI a prohledávání stavového prostoru',
      weekLabel: '2. týden',
      isProcessed: false,
      notes: `## Stavový prostor a přechody\n- Reprezentace úlohy jako grafu uzlů (stavů) a hran (akcí).\n- Algoritmus Minimax pro hry s nulovým součtem (např. šachy, piškvorky).`,
    },
    {
      id: 'topic_iskb02_1',
      ownerId,
      semesterId,
      courseId: 'course_ISKB02',
      title: 'Role a funkce moderních knihoven v informační společnosti',
      weekLabel: '1. přednáška',
      isProcessed: true,
      notes: `## Knihovna jako komunitní a vzdělávací centrum\n- Posun od pouhého uchovávání fondů k aktivní podpoře informační gramotnosti.\n- **Koncepce rozvoje knihoven ČR**: důraz na digitalizaci, rovný přístup k informacím a celoživotní učení.\n- Třetí místo (Ray Oldenburg): prostor mimo domov a práci, kde dochází k občanskému setkávání.`,
    },
    {
      id: 'topic_iskb03_1',
      ownerId,
      semesterId,
      courseId: 'course_ISKB03',
      title: 'Rešeršní strategie, Booleovské operátory a citační databáze',
      weekLabel: '1. seminář',
      isProcessed: false,
      notes: `## Tvorba dotazu v odborných databázích\n- Operátory: **AND** (průnik), **OR** (sjednocení/synonyma), **NOT** (vyloučení).\n- Zástupné znaky (truncation *, wildcard ?) a frázové vyhledávání v uvozovkách.\n- Citační databáze: Web of Science, Scopus, oborová LISA (Library and Information Science Abstracts).`,
    },
    {
      id: 'topic_iskb60_1',
      ownerId,
      semesterId,
      courseId: 'course_ISKB60',
      title: 'Úvod do studia KISK a informační vědy (DIKW pyramida)',
      weekLabel: 'Blok 1',
      isProcessed: true,
      notes: `## DIKW hierarchie\n- **Data**: surové symboly a fakta bez kontextu.\n- **Informace**: data zasazená do smysluplného kontextu (Kdo, Co, Kdy, Kde).\n- **Znalosti (Knowledge)**: propojení informací se zkušeností a schopností jednat (Jak).\n- **Moudrost (Wisdom)**: hodnotové posouzení a porozumění principům (Proč).`,
    },
  ];
}

export function getInitialTasks(ownerId: string, semesterId = DEFAULT_SEMESTER_ID): CourseTask[] {
  return [
    {
      id: 'task_ai_1',
      ownerId,
      semesterId,
      courseId: 'course_AI001',
      title: 'Dokončit cvičení v 1. a 2. kapitole kurzu Elements of AI',
      dueDate: '2026-10-20',
      description: 'Odevzdat screenshot certifikátu / splněných kapitol do odevzdávárny v IS MUNI.',
      priority: 'Střední',
      isCompleted: false,
    },
    {
      id: 'task_iskb03_1',
      ownerId,
      semesterId,
      courseId: 'course_ISKB03',
      title: 'Vypracovat rešeršní strategii na zvolené odborné téma',
      dueDate: '2026-10-28',
      description: 'Zvolit minimálně 3 odborné databáze, sepsat klíčová slova v ČJ a AJ a sestavit Booleovské dotazy.',
      priority: 'Vysoká',
      isCompleted: false,
    },
    {
      id: 'task_iskb04_1',
      ownerId,
      semesterId,
      courseId: 'course_ISKB04',
      title: 'Odevzdat teze a anotaci odborné přehledové stati',
      dueDate: '2026-11-05',
      description: 'Rozsah anotace 150–250 slov + seznam 5 primárních zdrojů dle citační normy ČSN ISO 690.',
      priority: 'Vysoká',
      isCompleted: false,
    },
    {
      id: 'task_iskb60_1',
      ownerId,
      semesterId,
      courseId: 'course_ISKB60',
      title: 'Reflexe z úvodního soustředění Prolegomena k oboru',
      dueDate: '2026-10-01',
      description: 'Odevzdáno v IS MUNI — splněno.',
      priority: 'Nízká',
      isCompleted: true,
    },
  ];
}

export function getInitialDates(ownerId: string, semesterId = DEFAULT_SEMESTER_ID): CourseDate[] {
  return [
    {
      id: 'date_iskb02_1',
      ownerId,
      semesterId,
      courseId: 'course_ISKB02',
      title: 'Exkurze do Moravské zemské knihovny',
      date: '2026-10-27',
      time: '10:00–11:40',
      room: 'MZK Brno, Kounicova 65a',
      teacher: 'PhDr. Petr Škyřík, Ph.D.',
      category: 'Seminář',
      isCompleted: false,
    },
    {
      id: 'date_iskb65_1',
      ownerId,
      semesterId,
      courseId: 'course_ISKB65',
      title: '1. setkání Bloku expertů — UX a design informačních služeb',
      date: '2026-10-16',
      time: '10:00–13:20',
      room: 'Posluchárna B2.13',
      teacher: 'Hostující přednášející KISK',
      category: 'Bloková výuka',
      isCompleted: false,
    },
    {
      id: 'date_phk_1',
      ownerId,
      semesterId,
      courseId: 'course_PHK0001',
      title: '1. řádný termín písemné zkoušky z filozofie',
      date: '2027-01-12',
      time: '09:00–10:30',
      room: 'Posluchárna A11',
      teacher: 'doc. PhDr. Josef Zouhar, CSc.',
      category: 'Zkouška',
      isCompleted: false,
    },
  ];
}
